#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../config.sh"
source "$DIR/../utils/user.sh"

name=$(basename "$1")
name=$(cleanup_username "$name")

if [ -z "$name" -o "$name" == "server.key" -o "$name" == "server.crt" ] ; then
	exit 1
fi

cat "$OPENVPN_KEY_BACKUP_DIR/$name"

exit 0
