#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/../config.sh"
source "$OPENVPN_VARS"

name="$1"

if [ -z "$name" ] ; then
	exit 1
fi

if [[ "$name" =~ \.\. ]] ; then
  exit 1
fi

if [[ "$name" =~ server\..+$ ]] ; then
  exit 1
fi

cat "$EASYRSA_PKI/$name"

exit 0