#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/user.sh"
source "$OPENVPN_VARS"

export KEY_NAME=$(cleanup_username "$1")
export KEY_EMAIL="$2"

export EASY_RSA="${EASY_RSA:-.}"

"$EASY_RSA/pkitool" $KEY_NAME
