#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/user.sh"
source "$OPENVPN_VARS"

name=$(cleanup_username "$1")

result=$("$EASY_RSA --batch revoke" "$name" 2>&1; exit 0)
echo "$result"
revoked=$(echo "$result" | grep "Data Base Updated" > /dev/null; echo "$?")
echo "Revoked: $revoked"

if [ "$revoked" != "0" ] ; then
	echo "Error: Can't revoke. Check easy-rsa output"
	exit 1
fi

"$EASY_RSA" gen-crl

exit 0