#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../utils/user.sh"
source "$DIR/../utils/easyrsa.sh"

name=$(cleanup_username "$1")

result="$(easyrsa_call --batch revoke "$name" 2>&1; exit 0)"
echo "$result"
echo ""
revoked=$(echo "$result" | grep "Data Base Updated" > /dev/null; echo "$?")
echo "Revoked: $revoked"

if [ "$revoked" != "0" ] ; then
	echo "Error: Can't revoke. Check easy-rsa output"
	exit 1
fi

easyrsa_call gen-crl

exit 0