#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/error.sh"
source "$DIR/../utils/user.sh"
source "$OPENVPN_VARS"

name=$(cleanup_username "$1")

if [ "$(user_exists $name)" == "0" ] ; then
  print_error "User does not exist: $name"
  exit 1
fi

if [ ! -f "$KEY_DIR/$name.crt" ] ; then
	print_error "Keys does not exist. Maybe already backuped?"
	exit 2
fi

sudo -u $OPENVPN_USER "$DIR/../binsudo/mv_key" "$name.key" "$OPENVPN_KEY_BACKUP_DIR/"
sudo -u $OPENVPN_USER "$DIR/../binsudo/mv_key" "$name.crt" "$OPENVPN_KEY_BACKUP_DIR/"
sudo -u $OPENVPN_USER "$DIR/../binsudo/mv_key" "$name.csr" "$OPENVPN_KEY_BACKUP_DIR/"

echo "Key backed up for user: $name"
echo ""

exit 0
