#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/error.sh"
source "$DIR/../utils/user.sh"
source "$OPENVPN_VARS"

name=$(cleanup_username "$1")

if [ "$(user_exists $name)" == "0" ] ; then
        print_error "User does not exist: $1"
        exit 1
fi

source "$DIR/../utils/zip_user_conf.sh"

zipfile=$(zip_user_conf "$name")
scp -f "$zipfile"
rm -rf "$(dirname "$zipfile")"
