#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/error.sh"
source "$DIR/../utils/user.sh"

name=$(cleanup_username "$1")

export EASYRSA_REQ_NAME="$name"
export EASYRSA_REQ_EMAIL="$2"

if [ "$(user_exists $name)" == "1" ] ; then
	print_error "User already exists: $1"
	exit 1
fi

sudo -H -u $OPENVPN_USER "$DIR/../binsudo/new_key" $EASYRSA_REQ_NAME $EASYRSA_REQ_EMAIL

if [ -n "$NOTIFY_ON_CHANGE_EMAIL" ] ; then
	if [ "$SEND_USER_CONF_IN_NOTIFICATION" == "yes" ] ; then
		source "$DIR/../utils/generate_user_conf.sh"
		cfile=$(generate_user_conf $EASYRSA_REQ_NAME)
	else
		cfile=""
	fi

	export USERNAME="$EASYRSA_REQ_NAME"
	export EMAIL="$EASYRSA_REQ_EMAIL"
	export THEME="$NEW_KEY_MAIL_THEME"

	message=$("$DIR/../$NEW_KEY_MAIL_TEMPLATE")

	source "$DIR/../utils/email.sh"
	result=$(send_email $NOTIFY_ON_CHANGE_EMAIL "$NEW_KEY_MAIL_THEME" "$message" "$cfile")

	if [ -n "$cfile" ] ; then
		rm -rf "$(dirname "$cfile")"
	fi

	if [ "$result" != "0" ] ; then
    print_error "Mail notification failed"
  fi
fi

echo "Key created for user: $EASYRSA_REQ_NAME"
echo ""

exit 0
