#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/../config.sh"
source "$DIR/../utils/error.sh"
source "$DIR/../utils/user.sh"

name=$(cleanup_username "$1")
EASYRSA_REQ_NAME="$name"

if [ "$(user_exists $name)" == "0" ] ; then
	print_error "User does not exist: $1"
	exit 1
fi

EASYRSA_REQ_EMAIL=$(user_email "$EASYRSA_REQ_NAME")

if [ -n "$EASYRSA_REQ_EMAIL" ] ; then
	source "$DIR/../utils/generate_user_conf.sh"
	cfile=$(generate_user_conf "$EASYRSA_REQ_NAME")

	export USERNAME="$EASYRSA_REQ_NAME"
	export EMAIL="$EASYRSA_REQ_EMAIL"
	export THEME="$NEW_KEY_MAIL_THEME"

	message=$("$DIR/../$NEW_KEY_MAIL_TEMPLATE")

	source "$DIR/../utils/email.sh"

	result=$(send_email "$EASYRSA_REQ_EMAIL" "$NEW_KEY_MAIL_THEME" "$message" "$cfile")

	rm -rf "$(dirname "$cfile")"

	if [ "$result" != "0" ] ; then
		print_error "SendMail failed"
		exit 2
	fi
else
	print_error "Can't find email for user: $EASYRSA_REQ_NAME"
	exit 1
fi

echo "User: $EASYRSA_REQ_NAME notified"
echo ""

exit 0
